# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            God Wars 2 Library
tagline:          'God Wars 2 Library'
description:      'Details for the awesome game of God Wars 2'
url:              https://mleo2003.github.io
baseurl:          /

author:
  name:           'Matthew Robinson'
  url:            https://mleo2003.github.io
